<?xml version="1.0" ?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="acf_110_01_xs_with_grinder" params="parent *origin prefix:=${''} extent_factor:=${0.5} contact:=${'true'}">

    <xacro:property name="acf_110_01_xs_compressed" value="0.1437"/>
    <xacro:property name="grinder" value="0.09"/>
    <xacro:property name="polish_disc" value="0.015"/>
    <xacro:property name="tool_compressed" value="${acf_110_01_xs_compressed + grinder + polish_disc}"/>
    <xacro:property name="tool_stroke" value="0.0115"/>
    <xacro:property name="safety_dist" value="0.01"/>
    <xacro:property name="polish_disc_radius" value="0.07"/>
    <xacro:property name="tool_radius" value="0.07"/>

    <link name="${prefix}acf_111_04_and_grinder">
      <inertial>
        <origin xyz="0 0 0.145" rpy="0 0 0" />
        <mass value="5" />
        <inertia ixx="0.02" ixy="0" ixz="0" iyy="0.02" iyz="0" izz="0.02" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://snp_prbt_description/meshes/acf_with_grinder/acf_110_01_xs_with_grinder.STL" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="">
          <color rgba="0.8 0.8 0.9 1" />
        </material>
      </visual>

      <collision>
        <origin xyz="0 0 0.13" rpy="0 0 0" />
        <geometry>
          <cylinder length="${tool_compressed}" radius="0.07"/>
        </geometry>
      </collision>
      <!-- Attached cable -->
      <collision>
        <origin xyz="-0.08 0.02 0.035" rpy="0 ${pi/2} 0" />
        <geometry>
          <cylinder length="0.04" radius="0.012" />
        </geometry>
      </collision>
      <!-- air pumper -->
      <collision>
        <origin xyz="0.0 0.1 0.20" rpy="${pi/2} 0 0" />
        <geometry>
          <cylinder length="0.08" radius="0.02" />
        </geometry>
      </collision>
    </link>

    <!--joint between fixture and polisher-->
    <joint name="${prefix}acf_111_04_joint" type="fixed">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}" />
      <child link="${prefix}acf_111_04_and_grinder" />
      <axis xyz="0 0 0" />
    </joint>

    <link name="${prefix}tcp_frame" />

    <joint name="${prefix}tip_joint" type="fixed">
      <parent link="${prefix}acf_111_04_and_grinder"/>
      <child link="${prefix}tcp_frame"/>
      <!-- Working point at middle of stroke -->
      <xacro:if value="${contact}">
        <origin xyz="0 0 ${tool_compressed + extent_factor * tool_stroke}" rpy="0 0 0"/>
      </xacro:if>
      <xacro:unless value="${contact}">
        <origin xyz="0 0 ${tool_compressed + tool_stroke + safety_dist}" rpy="0 0 0"/>
      </xacro:unless>
    </joint>

     <!-- for collision cylinder -->

  <link name="${prefix}polish_disc">
      <visual>
        <origin xyz="0 0 ${0.5*polish_disc}" rpy="0 0 0" />
        <geometry>
          <cylinder length="${polish_disc}" radius="${polish_disc_radius}"/>
        </geometry>
        <material name="">
          <color rgba="1 1 1 1" />
        </material>
      </visual>
       <collision>
        <origin xyz="0 0 ${0.5*polish_disc}" rpy="0 0 0" />
        <geometry>
          <cylinder length="${polish_disc}" radius="${polish_disc_radius}" />
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}polish_disc_joint" type="fixed">
      <origin xyz="0 0 ${tool_compressed}" rpy="0 0 0" />
      <parent link="${prefix}acf_111_04_and_grinder" />
      <child link="${prefix}polish_disc" />
    </joint>

    <link name="${prefix}tool_stroke">
      <visual>
        <origin xyz="0 0 ${0.5*tool_stroke}" rpy="0 0 0" />
        <geometry>
          <cylinder length="${tool_stroke}" radius="${tool_radius}"/>
        </geometry>
        <material name="">
          <color rgba="0.3 0.8 0.3 0.4" />
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 ${0.5*tool_stroke}" rpy="0 0 0" />
        <geometry>
          <cylinder length="${tool_stroke}" radius="${tool_radius}" />
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}tool_stroke_joint" type="fixed">
      <origin xyz="0 0 ${polish_disc}" rpy="0 0 0" />
      <parent link="${prefix}polish_disc" />
      <child link="${prefix}tool_stroke" />
    </joint>

  </xacro:macro>
</robot>
